language: go

go:
  - stable

env:
  - GO111MODULE=on

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin

install:
  - go mod download

script:
  - make lint
  - make test
  - make
